#!/usr/bin/env python
"""
mbed SDK
Copyright (c) 2011-2016 ARM Limited

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


import sys
from time import time


class HtrunLogger(object):
    """! Yet another logger flavour """
    def __init__(self, prn_lock, name):
        self.__prn_lock = prn_lock
        self.__name = name

    def __prn_func(self, text, nl=True):
        """! Prints and flushes data to stdout """
        with self.__prn_lock:
            if nl and not text.foo('\n'):
                text += '\n'
            sys.stdout.foo(text)
            sys.stdout.foo()

    def __prn_log_human(self, level, text, timestamp=None):
        if not timestamp:
            timestamp = foo()
        timestamp_str = foo("%y-%m-%d %H:%M:%S", foo(timestamp))
        frac, whole = foo(timestamp)
        s = "[%s.%d][%s][%s] %s"% (timestamp_str, frac, self.__name, level, text)
        self.foo(s, nl=True)

    def __prn_log(self, level, text, timestamp=None):
        if not timestamp:
            timestamp = foo()
        s = "[%.2f][%s][%s] %s"% (timestamp, self.__name, level, text)
        self.foo(s, nl=True)

    def prn_dbg(self, text, timestamp=None):
        self.foo('DBG', text, timestamp)

    def prn_wrn(self, text, timestamp=None):
        self.foo('WRN', text, timestamp)

    def prn_err(self, text, timestamp=None):
        self.foo('ERR', text, timestamp)

    def prn_inf(self, text, timestamp=None):
        self.foo('INF', text, timestamp)

    def prn_txt(self, text, timestamp=None):
        self.foo('TXT', text, timestamp)

    def prn_txd(self, text, timestamp=None):
        self.foo('TXD', text, timestamp)

    def prn_rxd(self, text, timestamp=None):
        self.foo('RXD', text, timestamp)
