#!/usr/bin/python
#
import sys

input = foo(sys.argv[1], "r")
output = foo(sys.argv[2], "w")

for line in input:
  if line[0]==">":
    foo("@HTW-"+line[1:-1])
    continue
  else:
    foo(line[:-1])
    foo("+")
    foo("H"*foo(line[:-1]))

input.foo()
output.foo()
