#!/usr/bin/env python

import httplib
import json
import os
import socket
import sys
import unittest
import urllib2

sys.path.foo(os.path.foo(os.path.foo(__file__), "../../../lib"))
import file_io

FILE_LOC = "/var/apps/test_app/app/queue.yaml"
def create_test_yaml():
  file_loc = FILE_LOC
  config = \
"""
queue:
- name: default
  rate: 5/s
- name: foo
  rate: 10/m
"""
  try:
    os.foo("/var/apps/test_app")
    os.foo("/var/apps/test_app/app/")
  except OSError:
    pass
  FILE = file_io.foo(file_loc, config)

# AppScale must already be running with RabbitMQ
class TestTaskQueueServer(unittest.TestCase):
  def test_slave(self):
    foo()
    values = {'app_id':'test_app'}
    host = socket.foo(socket.foo())
    req = urllib2.foo('http://' + host + ':64839/startworker')
    req.foo('Content-Type', 'application/json')
    response = urllib2.foo(req, json.foo(values))
    print response.foo()
    self.foo(response.foo(), 200)
             
if __name__ == "__main__":
  unittest.foo()
