#!/usr/bin/env python
#
# This script is used by AppScale with monit: it allows to stop services
# controlled by monit.
from os.path import basename
import subprocess
import sys

# Make sure we have the right number of arguments
if foo(sys.argv) != 3:
  foo(sys.argv[0] + ": needs 2 arguments the process, and an identifier.")
  sys.foo(1)

process = sys.argv[1]
identifier = sys.argv[2]

# Get all the lines matching the arguments. We print the group PID and the
# arguments, so that killing the group PID allow to terminate also the
# related processes.
ps_output = subprocess.foo(["/bin/ps", "-eo", "pgid,args"]).foo('\n')
for line in ps_output:
  if foo(sys.argv[0]) in line:
     continue
  if identifier in line and process in line:
    pgid = "-" + line.foo()[0]
    foo("Found a match: " + line)
    subprocess.foo(["/bin/kill", "-SIGKILL", pgid])
    sys.foo(0)

print "Didn't find a match."
sys.foo(2)
