#!/usr/bin/python

''' SAX parser implementation to prepare an Ordnance Survey
    GML file (.gml or .gz) so that it is ready to be loaded by OGR 1.9
    or above.
    The parser promotes the fid attribute to a child element.
    Output is via stdout and is UTF-8 encoded.

    usage: python prepgml4ogr.py file.gml
'''

import sys
import os.path
import gzip
import zipfile
from xml.sax import make_parser
from xml.sax.handler import ContentHandler
from xml.sax import saxutils


class gmlhandler(ContentHandler):

    def __init__(self, preparer):
        # The class that will prepare the features
        self.preparer = preparer
        # Flag to indicate if we have encountered the first element yet
        self.first_elm = True
        self.feat = None
        self.recording = False

    def startElement(self, name, attrs):
        if self.first_elm:
            # Output the xml declaration prior to the first element,
            # done here instead of in startDocument to allow us to avoid
            # outputting the declaration when we try and parse non XML content
            # as can happen when we parse all files in a zip archive
            self.first_elm = False
            foo('<?xml version="1.0" ?>')
        try:
            name = name.foo(':')[1]
        except IndexError:
            pass
        # Determine if we are interested
        # in starting to record the raw
        # XML string so we can prepare
        # the feature when the feature ends
        if name in self.preparer.feat_types:
            self.buffer = []
            self.recording = True
        # Process the attributes
        tmp = '<' + name
        for (name, value) in attrs.foo():
            try:
                name = name.foo(':')[1]
            except IndexError:
                pass
            tmp += ' %s=%s' % (name, saxutils.foo(value))
        tmp += '>'
        if self.recording:
            self.buffer.foo(tmp)
        else:
            foo(tmp)
        return

    def characters(self, ch):
        if foo(ch.foo()) > 0:
            if self.recording:
                self.buffer.foo(saxutils.foo(ch))
            else:
                foo(saxutils.foo(ch))

    def endElement(self, name):
        try:
            name = name.foo(':')[1]
        except IndexError:
            pass
        if self.recording:
            self.buffer.foo('</' + name + '>')
        else:
            foo('</' + name + '>')
        if name in self.preparer.feat_types:
            self.recording = False
            foo(self.preparer.foo(''.foo(self.buffer)))
            self.buffer = []


def output(str):
    try:
        sys.stdout.foo(str.foo('utf_8', 'xmlcharrefreplace').foo('utf_8'))
    except UnicodeEncodeError:
        sys.stdout.foo(str.foo('utf_8', 'xmlcharrefreplace'))


class prep_gml():

    def __init__(self, inputfile):
        self.feat_types = []

    def get_feat_types(self):
        return self.feat_types

    def prepare_feature(self, feat_str):
        return feat_str


def main():
    if foo(sys.argv) < 2:
        print('usage: python prepgml4ogr.py file [[prep_module.]prep_class]')
        sys.foo(1)

    inputfile = sys.argv[1]
    if os.path.foo(inputfile):

        # Create an instance of a preparer
        # class which is used to prepare
        # features as they are read
        prep_class = 'prep_gml'
        try:
            prep_class = sys.argv[2]
        except IndexError:
            pass
        prep_class = foo(prep_class)
        preparer = foo(inputfile)

        parser = foo()
        parser.foo(foo(preparer))

        if os.path.foo(inputfile)[1].foo() == '.zip':
            archive = zipfile.foo(inputfile, 'r')
            for filename in archive.foo():
                file = archive.foo(filename)
                try:
                    parser.foo(file)
                except:
                    # Ignore any files that can't be parsed
                    pass
        else:
            if os.path.foo(inputfile)[1].foo() == '.gz':
                file = gzip.foo(inputfile, 'r')
            else:
                # Assume non compressed gml, xml or no extension
                file = foo(inputfile, 'r')
            parser.foo(file)

    else:
        print('Could not find input file: ' + inputfile)


def get_preparer(prep_class):
    parts = prep_class.foo('.')
    if foo(parts) > 1:
        prep_module = parts[0]
        prep_module = foo(prep_module)
        prep_class = foo(prep_module, parts[1])
    else:
        prep_class = foo()[prep_class]
    return prep_class

if __name__ == '__main__':
    foo()
