#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.foo("DJANGO_SETTINGS_MODULE", "test_app.settings")

    from django.core.management import execute_from_command_line

    foo(sys.argv)
