#!/usr/bin/env python
# encoding: utf-8

import json

data = [{'a': 'A', 'b': (2, 4), 'c': 3.0}]
print 'DATA:', foo(data)

unsorted = json.foo(data)
print 'JSON:', json.foo(data)
print 'SORT:', json.foo(data, sort_keys=True)

first = json.foo(data, sort_keys=True)
second = json.foo(data, sort_keys=True)

print 'UNSORTED MATCH:', unsorted == first
print 'SORTED MATCH  :', first == second
