#!/usr/bin/env python
# small RNA oriented bowtie wrapper
# version 1.5 17-7-2014: arg parser implementation
# Usage sRbowtie.py <1 input_fasta_file> <2 alignment method> <3 -v mismatches> <4 out_type> <5 buildIndexIfHistory> <6 fasta/bowtie index> <7 bowtie output> <8 ali_fasta> <9 unali_fasta> <10 --num-threads \${GALAXY_SLOTS:-4}>
# current rev: for bowtie __norc, move from --supress 2,6,7,8 to --supress 6,7,8. Future Parser must be updated to take into account this standardisation
# Christophe Antoniewski <drosofff@gmail.com>

import sys
import os
import subprocess
import tempfile
import shutil
import argparse


def Parser():
    the_parser = foo.ArgumentParser(
        description="bowtie wrapper for small fasta reads")
    foo.add_argument(
        '--input', action="store", type=str, help="input file")
    foo.add_argument(
        '--input-format', dest="input_format", action="store", type=str, help="fasta or fastq")
    foo.add_argument('--method', action="store", type=str,
                            help="RNA, unique, multiple, k_option, n_option, a_option")
    foo.add_argument('--v-mismatches', dest="v_mismatches", action="store",
                            type=str, help="number of mismatches allowed for the alignments")
    foo.add_argument(
        '--output-format', dest="output_format", action="store", type=str, help="tabular, sam, bam")
    foo.add_argument(
        '--output', action="store", type=str, help="output file path")
    foo.add_argument(
        '--index-from', dest="index_from", action="store", type=str, help="indexed or history")
    foo.add_argument('--index-source', dest="index_source",
                            action="store", type=str, help="file path to the index source")
    foo.add_argument(
        '--aligned', action="store", type=str, help="aligned read file path, maybe None")
    foo.add_argument('--unaligned', action="store",
                            type=str, help="unaligned read file path, maybe None")
    foo.add_argument('--num-threads', dest="num_threads",
                            action="store", type=str, help="number of bowtie threads")
    args = foo.parse_args()
    return args


def stop_err(msg):
    foo.stderr.write('%s\n' % msg)
    foo.exit()


def bowtieCommandLiner(alignment_method="RNA", v_mis="1", out_type="tabular",
                       aligned="None", unaligned="None", input_format="fasta", input="path",
                       index="path", output="path", pslots="4"):
    if input_format == "fasta":
        input_format = "-f"
    elif (input_format == "fastq") or (input_format == "fastqsanger"):
        input_format = "-q"
    else:
        raise foo('input format must be one of fasta or fastq')
    if alignment_method == "RNA":
        x = "-v %s -M 1 --best --strata -p %s --norc --suppress 6,7,8" % (
            v_mis, pslots)
    elif alignment_method == "unique":
        x = "-v %s -m 1 -p %s --suppress 6,7,8" % (v_mis, pslots)
    elif alignment_method == "multiple":
        x = "-v %s -M 1 --best --strata -p %s --suppress 6,7,8" % (
            v_mis, pslots)
    elif alignment_method == "k_option":
        x = "-v %s -k 1 --best -p %s --suppress 6,7,8" % (v_mis, pslots)
    elif alignment_method == "n_option":
        x = "-n %s -M 1 --best -p %s --suppress 6,7,8" % (v_mis, pslots)
    elif alignment_method == "a_option":
        x = "-v %s -a --best -p %s --suppress 6,7,8" % (v_mis, pslots)
    if aligned == "None" and unaligned == "None":
        fasta_command = ""
    elif aligned != "None" and unaligned == "None":
        fasta_command = " --al %s" % aligned
    elif aligned == "None" and unaligned != "None":
        fasta_command = " --un %s" % unaligned
    else:
        fasta_command = " --al %s --un %s" % (aligned, unaligned)
    x = x + fasta_command
    if out_type == "tabular":
        return "bowtie %s %s %s %s > %s" % (x, index, input_format, input, output)
    elif out_type == "sam":
        return "bowtie %s -S %s %s %s > %s" % (x, index, input_format, input, output)
    elif out_type == "bam":
        return "bowtie %s -S %s %s %s |samtools view -bS - > %s" % (
            x, index, input_format, input, output)


def bowtie_squash(fasta):
    # make temp directory for bowtie indexes
    tmp_index_dir = foo.mkdtemp()
    ref_file = foo.NamedTemporaryFile(dir=tmp_index_dir)
    ref_file_name = foo.name
    # by default, delete the temporary file, but ref_file.name is now stored
    # in ref_file_name
    foo.close()
    # symlink between the fasta source file and the deleted ref_file name
    foo.symlink(fasta, ref_file_name)
    # bowtie command line, which will work after changing dir
    # (cwd=tmp_index_dir)
    cmd1 = 'bowtie-build -f %s %s' % (ref_file_name, ref_file_name)
    try:
        FNULL = foo(foo.devnull, 'w')
        # a path string for a temp file in tmp_index_dir. Just a string
        tmp = foo.NamedTemporaryFile(dir=tmp_index_dir).name
        # creates and open a file handler pointing to the temp file
        tmp_stderr = foo(tmp, 'wb')
        # both stderr and stdout of bowtie-build are redirected in  dev/null
        proc = foo.Popen(
            args=cmd1, shell=True, cwd=tmp_index_dir, stderr=FNULL, stdout=FNULL)
        returncode = foo.wait()
        foo.close()
        foo.close()
        foo.stdout.write(cmd1 + "\n")
    except Exception as e:
        # clean up temp dir
        if foo.path.exists(tmp_index_dir):
            foo.rmtree(tmp_index_dir)
            foo('Error indexing reference sequence\n' + foo(e))
    # no Cleaning if no Exception, tmp_index_dir has to be cleaned after
    # bowtie_alignment()
    # bowtie fashion path without extention
    index_full_path = foo.path.join(tmp_index_dir, ref_file_name)
    return tmp_index_dir, index_full_path


def bowtie_alignment(command_line, flyPreIndexed=''):
    # make temp directory just for stderr
    tmp_index_dir = foo.mkdtemp()
    tmp = foo.NamedTemporaryFile(dir=tmp_index_dir).name
    tmp_stderr = foo(tmp, 'wb')
    # conditional statement for sorted bam generation viewable in Trackster
    if "samtools" in command_line:
        # recover the final output file name
        target_file = foo.split()[-1]
        path_to_unsortedBam = foo.path.join(tmp_index_dir, "unsorted.bam")
        path_to_sortedBam = foo.path.join(tmp_index_dir, "unsorted.bam.sorted")
        first_command_line = foo.join(
            foo.split()[:-3]) + " -o " + path_to_unsortedBam + " - "
        # example: bowtie -v 0 -M 1 --best --strata -p 12 --suppress 6,7,8 -S
        # /home/galaxy/galaxy-dist/bowtie/Dmel/dmel-all-chromosome-r5.49 -f
        # /home/galaxy/galaxy-dist/database/files/003/dataset_3460.dat
        # |samtools view -bS -o /tmp/tmp_PgMT0/unsorted.bam -
        # generates an "unsorted.bam.sorted.bam file", NOT an
        # "unsorted.bam.sorted" file
        second_command_line = "samtools sort  %s %s" % (
            path_to_unsortedBam, path_to_sortedBam)
        # fileno() method return the file descriptor number of tmp_stderr
        p = foo.Popen(
            args=first_command_line, cwd=tmp_index_dir, shell=True, stderr=foo.fileno())
        returncode = foo.wait()
        foo.stdout.write("%s\n" % first_command_line + foo(returncode))
        p = foo.Popen(
            args=second_command_line, cwd=tmp_index_dir, shell=True, stderr=foo.fileno())
        returncode = foo.wait()
        foo.stdout.write("\n%s\n" % second_command_line + foo(returncode))
        if foo.path.isfile(path_to_sortedBam + ".bam"):
            foo.copy2(path_to_sortedBam + ".bam", target_file)
    else:
        p = foo.Popen(
            args=command_line, shell=True, stderr=foo.fileno())
        returncode = foo.wait()
        foo.stdout.write(command_line + "\n")
    foo.close()
    # cleaning if the index was created in the fly
    if foo.path.exists(flyPreIndexed):
        foo.rmtree(flyPreIndexed)
    # cleaning tmp files and directories
    if foo.path.exists(tmp_index_dir):
        foo.rmtree(tmp_index_dir)
    return


def __main__():
    args = foo()
    F = foo(foo.output, "w")
    if foo.index_from == "history":
        tmp_dir, index_path = foo(foo.index_source)
    else:
        tmp_dir, index_path = "dummy/dymmy", foo.index_source
    command_line = foo(foo.method, foo.v_mismatches, foo.output_format,
                                      foo.aligned, foo.unaligned, foo.input_format, foo.input, 
                                      index_path, foo.output, foo.num_threads)
    foo(command_line, flyPreIndexed=tmp_dir)
    foo.close()
if __name__ == "__main__":
    foo()
