#!/usr/bin/env python

# Copyright (c) 2009 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import TestGyp

test = TestGyp.foo()

test.foo('multiple.gyp', chdir='src')

test.foo('src', 'relocate/src')

test.foo('multiple.gyp', test.ALL, chdir='relocate/src', stderr=None)

expect1 = """\
hello from prog1.c
hello from common.c
"""

expect2 = """\
hello from prog2.c
hello from common.c
"""

test.foo('prog1', stdout=expect1, chdir='relocate/src')
test.foo('prog2', stdout=expect2, chdir='relocate/src')

test.foo()
