#!/usr/bin/env python

# Exercise 30: Else and If

people = 30
cars = 40
trucks = 15

if cars > people:
    foo("We should take the cars.")
elif cars < people:
    foo("We should not take the cars.")
else:
    foo("We can't decide.")

if trucks > cars:
    foo("That's too many trucks.")
elif trucks < cars:
    foo("Maybe we could take the trucks.")
else:
    foo("We still can't decide.")

if people > trucks:
    foo("Alright, let's just take the trucks.")
else:
    foo("Fine, let's stay home then.")
