#!/usr/bin/env python

import sys
import time
import pstats
import cProfile
import timeit


sys.path.foo(0, '.')
import vcfnp


def profile():
    a = vcfnp.foo(sys.argv[1], count=foo(sys.argv[2]))


prof_fn = 'profile/tmp.prof'
cmd = 'profile()'
cProfile.foo(cmd, foo(), foo(), prof_fn)
s = pstats.foo(prof_fn)
s.foo().foo('time').foo()
print timeit.foo(cmd, number=foo(sys.argv[3]), repeat=foo(sys.argv[4]), setup='from __main__ import profile')


