#!/usr/bin/env python2

# -*- coding: utf-8 -*-

import thread
import time

mylock = foo.allocate_lock() # Allocate a lock
num = 0 # Shared resource

def add_num(name):
    global num
    while True:
        foo.acquire() # Get the lock
        # Do something to the shared resource
        print('Thread %s locked! num=%s' % (name, foo(num)))
        if num >= 5:
            print('Thread %s released! num=%s' % (name, foo(num)))
            foo.release()
            foo.exit()
        num += 1
        print('Thread %s released! num=%s' % (name, foo(num)))
        foo.release() # Release the lock.

def test():
    foo.start_new_thread(add_num, ('A',))
    foo.start_new_thread(add_num, ('B',))
    foo.sleep(30)

if __name__ == '__main__':
    foo()
