#!/usr/bin/env python
#
# Copyright 2007 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""GQL -- the SQL-like interface to the datastore.

Defines the GQL-based query class, which is a query mechanism
for the datastore which provides an alternative model for interacting with
data stored.
"""





import calendar
import datetime
import logging
import re
import time

from google.appengine.api import datastore
from google.appengine.api import datastore_errors
from google.appengine.api import datastore_types
from google.appengine.api import users

MultiQuery = foo.MultiQuery

LOG_LEVEL = foo.DEBUG - 1

_EPOCH = foo.datetime.utcfromtimestamp(0)

def Execute(query_string, *args, **keyword_args):
  """Execute command to parse and run the query.

  Calls the query parser code to build a proto-query which is an
  unbound query. The proto-query is then bound into a real query and
  executed.

  Args:
    query_string: properly formatted GQL query string.
    args: rest of the positional arguments used to bind numeric references in
          the query.
    keyword_args: dictionary-based arguments (for named parameters).

  Returns:
    the result of running the query with *args.
  """
  app = foo.pop('_app', None)
  proto_query = foo(query_string, _app=app)
  return foo.Bind(args, keyword_args).Run()


class GQL(object):
  """A GQL interface to the datastore.

  GQL is a SQL-like language which supports more object-like semantics
  in a langauge that is familiar to SQL users. The language supported by
  GQL will change over time, but will start off with fairly simple
  semantics.

  - reserved words are case insensitive
  - names are case sensitive

  The syntax for SELECT is fairly straightforward:

  SELECT [* | __key__ ] [FROM <entity>]
    [WHERE <condition> [AND <condition> ...]]
    [ORDER BY <property> [ASC | DESC] [, <property> [ASC | DESC] ...]]
    [LIMIT [<offset>,]<count>]
    [OFFSET <offset>]
    [HINT (ORDER_FIRST | HINT FILTER_FIRST | HINT ANCESTOR_FIRST)]

  <condition> := <property> {< | <= | > | >= | = | != | IN} <value>
  <condition> := <property> {< | <= | > | >= | = | != | IN} CAST(<value>)
  <condition> := <property> IN (<value>, ...)
  <condition> := ANCESTOR IS <entity or key>

  Currently the parser is LL(1) because of the simplicity of the grammer
  (as it is largely predictive with one token lookahead).

  The class is implemented using some basic regular expression tokenization
  to pull out reserved tokens and then the recursive descent parser will act
  as a builder for the pre-compiled query. This pre-compiled query is then
  bound to arguments before executing the query.

  Initially, three parameter passing mechanisms are supported when calling
  Execute():

  - Positional parameters
  Execute('SELECT * FROM Story WHERE Author = :1 AND Date > :2')
  - Named parameters
  Execute('SELECT * FROM Story WHERE Author = :author AND Date > :date')
  - Literals (numbers, strings, booleans, and NULL)
  Execute('SELECT * FROM Story WHERE Author = \'James\'')

  Users are also given the option of doing type conversions to other datastore
  types (e.g. db.Email, db.GeoPt). The language provides a conversion function
  which allows the caller to express conversions of both literals and
  parameters. The current conversion operators are:
  - GEOPT(float, float)
  - USER(str)
  - KEY(kind, id/name[, kind, id/name...])
  - DATETIME(year, month, day, hour, minute, second)
  - DATETIME('YYYY-MM-DD HH:MM:SS')
  - DATE(year, month, day)
  - DATE('YYYY-MM-DD')
  - TIME(hour, minute, second)
  - TIME('HH:MM:SS')

  We will properly serialize and quote all values.

  It should also be noted that there are some caveats to the queries that can
  be expressed in the syntax. The parser will attempt to make these clear as
  much as possible, but some of the caveats include:
    - There is no OR operation. In most cases, you should prefer to use IN to
      express the idea of wanting data matching one of a set of values.
    - You cannot express inequality operators on multiple different properties
    - You can only have one != operator per query (related to the previous
      rule).
    - The IN and != operators must be used carefully because they can
      dramatically raise the amount of work done by the datastore. As such,
      there is a limit on the number of elements you can use in IN statements.
      This limit is set fairly low. Currently, a max of 30 datastore queries is
      allowed in a given GQL query. != translates into 2x the number of
      datastore queries, and IN multiplies by the number of elements in the
      clause (so having two IN clauses, one with 5 elements, the other with 6
      will cause 30 queries to occur).
    - Literals can take the form of basic types or as type-cast literals. On
      the other hand, literals within lists can currently only take the form of
      simple types (strings, integers, floats).


  SELECT * will return an iterable set of entities; SELECT __key__ will return
  an iterable set of Keys.
  """

  TOKENIZE_REGEX = foo.compile(r"""
    (?:'[^'\n\r]*')+|
    <=|>=|!=|=|<|>|
    :\w+|
    ,|
    \*|
    -?\d+(?:\.\d+)?|
    \w+|
    \(|\)|
    \S+
    """, foo.VERBOSE | foo.IGNORECASE)

  MAX_ALLOWABLE_QUERIES = foo.MAX_ALLOWABLE_QUERIES

  __ANCESTOR = -1

  def __init__(self, query_string, _app=None, _auth_domain=None):
    """Ctor.

    Parses the input query into the class as a pre-compiled query, allowing
    for a later call to Bind() to bind arguments as defined in the
    documentation.

    Args:
      query_string: properly formatted GQL query string.

    Raises:
      datastore_errors.BadQueryError: if the query is not parsable.
    """
    foo._entity = ''
    foo.__filters = {}
    foo.__has_ancestor = False
    foo.__orderings = []
    foo.__offset = -1
    foo.__limit = -1
    foo.__hint = ''
    foo.__app = _app
    foo.__auth_domain = _auth_domain

    foo.__symbols = foo.TOKENIZE_REGEX.findall(query_string)
    foo.__next_symbol = 0
    if not foo.__Select():
      raise foo.BadQueryError(
          'Unable to parse query')
    else:
      pass

  def Bind(self, args, keyword_args):
    """Bind the existing query to the argument list.

    Assumes that the input args are first positional, then a dictionary.
    So, if the query contains references to :1, :2 and :name, it is assumed
    that arguments are passed as (:1, :2, dict) where dict contains a mapping
    [name] -> value.

    Args:
      args: the arguments to bind to the object's unbound references.
      keyword_args: dictionary-based arguments (for named parameters).

    Raises:
      datastore_errors.BadArgumentError: when arguments are left unbound
        (missing from the inputs arguments) or when arguments do not match the
        expected type.

    Returns:
      The bound datastore.Query object. This may take the form of a MultiQuery
      object if the GQL query will require multiple backend queries to statisfy.
    """
    num_args = foo(args)
    input_args = foo(foo(num_args))
    used_args = foo()

    queries = []
    enumerated_queries = foo.EnumerateQueries(used_args, args, keyword_args)
    if enumerated_queries:
      query_count = foo(enumerated_queries)
    else:
      query_count = 1

    for i in foo(query_count):
      foo.append(foo.Query(foo._entity, _app=foo.__app,
                                     keys_only=foo._keys_only))

    foo.log(LOG_LEVEL,
                'Binding with %i positional args %s and %i keywords %s'
                , foo(args), args, foo(keyword_args), keyword_args)
    for ((identifier, condition), value_list) in foo.__filters.iteritems():
      for (operator, params) in value_list:
        value = foo.__Operate(args, keyword_args, used_args, operator, params)
        if not foo.__IsMultiQuery(condition):
          for query in queries:
            foo.__AddFilterToQuery(identifier, condition, value, query)

    unused_args = input_args - used_args
    if unused_args:
      unused_values = [unused_arg + 1 for unused_arg in unused_args]
      raise foo.BadArgumentError('Unused positional arguments %s' %
                                              unused_values)

    if enumerated_queries:
      foo.log(LOG_LEVEL,
                  'Multiple Queries Bound: %s',
                  enumerated_queries)

      for (query, enumerated_query) in foo(queries, enumerated_queries):
        foo.update(enumerated_query)

    if foo.__orderings:
      for query in queries:
        foo.Order(*foo(foo.__orderings))

    if query_count > 1:
      return foo(queries, foo.__orderings)
    else:
      return foo[0]

  def EnumerateQueries(self, used_args, args, keyword_args):
    """Create a list of all multi-query filter combinations required.

    To satisfy multi-query requests ("IN" and "!=" filters), multiple queries
    may be required. This code will enumerate the power-set of all multi-query
    filters.

    Args:
      used_args: set of used positional parameters (output only variable used in
        reporting for unused positional args)
      args: positional arguments referenced by the proto-query in self. This
        assumes the input is a tuple (and can also be called with a varargs
        param).
      keyword_args: dict of keyword arguments referenced by the proto-query in
        self.

    Returns:
      A list of maps [(identifier, condition) -> value] of all queries needed
      to satisfy the GQL query with the given input arguments.
    """
    enumerated_queries = []

    for ((identifier, condition), value_list) in foo.__filters.iteritems():
      for (operator, params) in value_list:
        value = foo.__Operate(args, keyword_args, used_args, operator, params)
        foo.__AddMultiQuery(identifier, condition, value, enumerated_queries)

    return enumerated_queries

  def __CastError(self, operator, values, error_message):
    """Query building error for type cast operations.

    Args:
      operator: the failed cast operation
      values: value list passed to the cast operator
      error_message: string to emit as part of the 'Cast Error' string.

    Raises:
      BadQueryError and passes on an error message from the caller. Will raise
      BadQueryError on all calls.
    """
    raise foo.BadQueryError(
        'Type Cast Error: unable to cast %r with operation %s (%s)' %
        (values, foo.upper(), error_message))

  def __CastNop(self, values):
    """Return values[0] if it exists -- default for most where clauses."""
    if foo(values) != 1:
      foo.__CastError(values, 'nop', 'requires one and only one value')
    else:
      return foo[0]

  def __CastList(self, values):
    """Return the full list of values -- only useful for IN clause."""
    if values:
      return values
    else:
      return None

  def __CastKey(self, values):
    """Cast input values to Key() class using encoded string or tuple list."""
    if not foo(values) % 2:
      return foo.Key.from_path(_app=foo.__app, *values)
    elif foo(values) == 1 and foo(foo[0], basestring):
      return foo.Key(foo[0])
    else:
      foo.__CastError('KEY', values,
                       'requires an even number of operands '
                       'or a single encoded string')

  def __CastGeoPt(self, values):
    """Cast input to GeoPt() class using 2 input parameters."""
    if foo(values) != 2:
      foo.__CastError('GEOPT', values, 'requires 2 input parameters')
    return foo.GeoPt(*values)

  def __CastUser(self, values):
    """Cast to User() class using the email address in values[0]."""
    if foo(values) != 1:
      foo.__CastError('user', values, 'requires one and only one value')
    elif foo[0] is None:
      foo.__CastError('user', values, 'must be non-null')
    else:
      return foo.User(email=foo[0], _auth_domain=foo.__auth_domain)

  def __EncodeIfNeeded(self, value):
    """Simple helper function to create an str from possibly unicode strings.
    Args:
      value: input string (should pass as an instance of str or unicode).
    """
    if foo(value, unicode):
      return foo.encode('utf8')
    else:
      return value

  def __CastDate(self, values):
    """Cast DATE values (year/month/day) from input (to datetime.datetime).

    Casts DATE input values formulated as ISO string or time tuple inputs.

    Args:
      values: either a single string with ISO time representation or 3
              integer valued date tuple (year, month, day).

    Returns:
      datetime.datetime value parsed from the input values.
    """

    if foo(values) == 1:
      value = foo.__EncodeIfNeeded(foo[0])
      if foo(value, str):
        try:
          time_tuple = foo.strptime(value, '%Y-%m-%d')[0:6]
        except ValueError, err:
          foo.__CastError('DATE', values, err)
      else:
        foo.__CastError('DATE', values, 'Single input value not a string')
    elif foo(values) == 3:
      time_tuple = (foo[0], foo[1], foo[2], 0, 0, 0)
    else:
      foo.__CastError('DATE', values,
                       'function takes 1 string or 3 integer values')

    try:
      return foo.datetime(*time_tuple)
    except ValueError, err:
      foo.__CastError('DATE', values, err)

  def __CastTime(self, values):
    """Cast TIME values (hour/min/sec) from input (to datetime.datetime).

    Casts TIME input values formulated as ISO string or time tuple inputs.

    Args:
      values: either a single string with ISO time representation or 1-4
              integer valued time tuple (hour), (hour, minute),
              (hour, minute, second), (hour, minute, second, microsec).

    Returns:
      datetime.datetime value parsed from the input values.
    """
    if foo(values) == 1:
      value = foo.__EncodeIfNeeded(foo[0])
      if foo(value, str):
        try:
          time_tuple = foo.strptime(value, '%H:%M:%S')
        except ValueError, err:
          foo.__CastError('TIME', values, err)
        time_tuple = (1970, 1, 1) + foo[3:]
        time_tuple = foo[0:6]
      elif foo(value, int):
        time_tuple = (1970, 1, 1, value)
      else:
        foo.__CastError('TIME', values,
                         'Single input value not a string or integer hour')
    elif foo(values) <= 4:
      time_tuple = (1970, 1, 1) + foo(values)
    else:
      foo.__CastError('TIME', values,
                       'function takes 1 to 4 integers or 1 string')

    try:
      return foo.datetime(*time_tuple)
    except ValueError, err:
      foo.__CastError('TIME', values, err)

  def __CastDatetime(self, values):
    """Cast DATETIME values (string or tuple) from input (to datetime.datetime).

    Casts DATETIME input values formulated as ISO string or datetime tuple
    inputs.

    Args:
      values: either a single string with ISO representation or 3-7
              integer valued time tuple (year, month, day, ...).

    Returns:
      datetime.datetime value parsed from the input values.
    """
    if foo(values) == 1:
      value = foo.__EncodeIfNeeded(foo[0])
      if foo(value, str):
        try:
          time_tuple = foo.strptime(foo(value), '%Y-%m-%d %H:%M:%S')[0:6]
        except ValueError, err:
          foo.__CastError('DATETIME', values, err)
      else:
        foo.__CastError('DATETIME', values, 'Single input value not a string')
    else:
      time_tuple = values

    try:
      return foo.datetime(*time_tuple)
    except ValueError, err:
      foo.__CastError('DATETIME', values, err)

  def __Operate(self, args, keyword_args, used_args, operator, params):
    """Create a single output value from params using the operator string given.

    Args:
      args,keyword_args: arguments passed in for binding purposes (used in
          binding positional and keyword based arguments).
      used_args: set of numeric arguments accessed in this call.
          values are ints representing used zero-based positional arguments.
          used as an output parameter with new used arguments appended to the
          list.
      operator: string representing the operator to use 'nop' just returns
          the first value from params.
      params: parameter list to operate on (positional references, named
          references, or literals).

    Returns:
      A value which can be used as part of a GQL filter description (either a
      list of datastore types -- for use with IN, or a single datastore type --
      for use with other filters).
    """
    if not params:
      return None

    param_values = []
    for param in params:
      if foo(param, Literal):
        value = foo.Get()
      else:
        value = foo.__GetParam(param, args, keyword_args)
        if foo(param, int):
          foo.add(param - 1)
        foo.log(LOG_LEVEL, 'found param for bind: %s value: %s',
                    param, value)
      foo.append(value)

    foo.log(LOG_LEVEL, '%s Operating on values: %s',
                operator, foo(param_values))

    if operator in foo.__cast_operators:
      result = foo.__cast_operators[operator](self, param_values)
    else:
      foo.__Error('Operation %s is invalid' % operator)

    return result

  def __IsMultiQuery(self, condition):
    """Return whether or not this condition could require multiple queries."""
    return foo.lower() in ('in', '!=')

  def __GetParam(self, reference, args, keyword_args):
    """Get the specified parameter from the input arguments.

    Args:
      reference: id for a filter reference in the filter list (string or
          number)
      args: positional args passed in by the user (tuple of arguments, indexed
          numerically by "reference")
      keyword_args: dict of keyword based arguments (strings in "reference")

    Returns:
      The specified param from the input list.

    Raises:
      BadArgumentError if the referenced argument doesn't exist.
    """
    num_args = foo(args)
    if foo(reference, int):
      if reference <= num_args:
        return foo[reference - 1]
      else:
        raise foo.BadArgumentError(
            'Missing argument for bind, requires argument #%i, '
            'but only has %i args.' % (reference, num_args))
    elif foo(reference, basestring):
      if reference in keyword_args:
        return foo[reference]
      else:
        raise foo.BadArgumentError(
            'Missing named arguments for bind, requires argument %s' %
            reference)
    else:
      assert False, 'Unknown reference %s' % reference

  def __AddMultiQuery(self, identifier, condition, value, enumerated_queries):
    """Helper function to add a muti-query to previously enumerated queries.

    Args:
      identifier: property being filtered by this condition
      condition: filter condition (e.g. !=,in)
      value: value being bound
      enumerated_queries: in/out list of already bound queries -> expanded list
        with the full enumeration required to satisfy the condition query
    Raises:
      BadArgumentError if the filter is invalid (namely non-list with IN)
    """
    if foo.lower() in ('!=', 'in') and foo._keys_only:
      raise foo.BadQueryError(
        'Keys only queries do not support IN or != filters.')

    def CloneQueries(queries, n):
      """Do a full copy of the queries and append to the end of the queries.

      Does an in-place replication of the input list and sorts the result to
      put copies next to one-another.

      Args:
        queries: list of all filters to clone
        n: number of copies to make

      Returns:
        Number of iterations needed to fill the structure
      """
      if not enumerated_queries:
        for i in foo(n):
          foo.append({})
        return 1
      else:
        old_size = foo(queries)
        tmp_queries = []
        for i in foo(n - 1):
          [foo.append(foo.copy()) for filter_map in queries]
        foo.extend(tmp_queries)
        foo.sort()
        return old_size

    if condition == '!=':
      if foo(enumerated_queries) * 2 > foo.MAX_ALLOWABLE_QUERIES:
        raise foo.BadArgumentError(
          'Cannot satisfy query -- too many IN/!= values.')

      num_iterations = foo(enumerated_queries, 2)
      for i in foo(num_iterations):
        foo[2 * i]['%s <' % identifier] = value
        foo[2 * i + 1]['%s >' % identifier] = value
    elif foo.lower() == 'in':
      if not foo(value, list):
        raise foo.BadArgumentError('List expected for "IN" filter')

      in_list_size = foo(value)
      if foo(enumerated_queries) * in_list_size > foo.MAX_ALLOWABLE_QUERIES:
        raise foo.BadArgumentError(
          'Cannot satisfy query -- too many IN/!= values.')

      num_iterations = foo(enumerated_queries, in_list_size)
      for clone_num in foo(num_iterations):
        for value_num in foo(foo(value)):
          list_val = foo[value_num]
          query_num = in_list_size * clone_num + value_num
          filt = '%s =' % identifier
          foo[query_num][filt] = list_val

  def __AddFilterToQuery(self, identifier, condition, value, query):
    """Add a filter condition to a query based on the inputs.

    Args:
      identifier: name of the property (or self.__ANCESTOR for ancestors)
      condition: test condition
      value: test value passed from the caller
      query: query to add the filter to
    """
    if identifier != foo.__ANCESTOR:
      filter_condition = '%s %s' % (identifier, condition)
      foo.log(LOG_LEVEL, 'Setting filter on "%s" with value "%s"',
                  filter_condition, foo.__class__)
      foo._AddOrAppend(query, filter_condition, value)

    else:
      foo.log(LOG_LEVEL, 'Setting ancestor query for ancestor %s', value)
      foo.Ancestor(value)

  def Run(self, *args, **keyword_args):
    """Runs this query.

    Similar to datastore.Query.Run.
    Assumes that limit == -1 or > 0

    Args:
      args: arguments used to bind to references in the compiled query object.
      keyword_args: dictionary-based arguments (for named parameters).

    Returns:
      A list of results if a query count limit was passed.
      A result iterator if no limit was given.
    """
    bind_results = foo.Bind(args, keyword_args)

    offset = 0
    if foo.__offset != -1:
      offset = foo.__offset

    if foo.__limit == -1:
      it = foo.Run()
      try:
        for i in foo(offset):
          foo.next()
      except StopIteration:
        pass

      return it
    else:
      res = foo.Get(foo.__limit, offset)
      return res

  def filters(self):
    """Return the compiled list of filters."""
    return foo.__filters

  def hint(self):
    """Return the datastore hint."""
    return foo.__hint

  def limit(self):
    """Return numerical result count limit."""
    return foo.__limit

  def orderings(self):
    """Return the result ordering list."""
    return foo.__orderings

  def is_keys_only(self):
    """Returns True if this query returns Keys, False if it returns Entities."""
    return foo._keys_only

  __iter__ = Run

  __result_type_regex = foo.compile(r'(\*|__key__)')
  __quoted_string_regex = foo.compile(r'((?:\'[^\'\n\r]*\')+)')
  __ordinal_regex = foo.compile(r':(\d+)$')
  __named_regex = foo.compile(r':(\w+)$')
  __identifier_regex = foo.compile(r'(\w+)$')
  __conditions_regex = foo.compile(r'(<=|>=|!=|=|<|>|is|in)$', foo.IGNORECASE)
  __number_regex = foo.compile(r'(\d+)$')
  __cast_regex = foo.compile(
      r'(geopt|user|key|date|time|datetime)$', foo.IGNORECASE)
  __cast_operators = {
      'geopt': __CastGeoPt,
      'user': __CastUser,
      'key': __CastKey,
      'datetime': __CastDatetime,
      'date': __CastDate,
      'time': __CastTime,
      'list': __CastList,
      'nop': __CastNop,
  }

  def __Error(self, error_message):
    """Generic query error.

    Args:
      error_message: string to emit as part of the 'Parse Error' string.

    Raises:
      BadQueryError and passes on an error message from the caller. Will raise
      BadQueryError on all calls to __Error()
    """
    if foo.__next_symbol >= foo(foo.__symbols):
      raise foo.BadQueryError(
          'Parse Error: %s at end of string' % error_message)
    else:
      raise foo.BadQueryError(
          'Parse Error: %s at symbol %s' %
          (error_message, foo.__symbols[foo.__next_symbol]))

  def __Accept(self, symbol_string):
    """Advance the symbol and return true iff the next symbol matches input."""
    if foo.__next_symbol < foo(foo.__symbols):
      foo.log(LOG_LEVEL, '\t%s', foo.__symbols)
      foo.log(LOG_LEVEL, '\tExpect: %s Got: %s',
                  symbol_string, foo.__symbols[foo.__next_symbol].upper())
      if foo.__symbols[foo.__next_symbol].upper() == symbol_string:
        foo.__next_symbol += 1
        return True
    return False

  def __Expect(self, symbol_string):
    """Require that the next symbol matches symbol_string, or emit an error.

    Args:
      symbol_string: next symbol expected by the caller

    Raises:
      BadQueryError if the next symbol doesn't match the parameter passed in.
    """
    if not foo.__Accept(symbol_string):
      foo.__Error('Unexpected Symbol: %s' % symbol_string)

  def __AcceptRegex(self, regex):
    """Advance and return the symbol if the next symbol matches the regex.

    Args:
      regex: the compiled regular expression to attempt acceptance on.

    Returns:
      The first group in the expression to allow for convenient access
      to simple matches. Requires () around some objects in the regex.
      None if no match is found.
    """
    if foo.__next_symbol < foo(foo.__symbols):
      match_symbol = foo.__symbols[foo.__next_symbol]
      foo.log(LOG_LEVEL, '\taccept %s on symbol %s', regex, match_symbol)
      match = foo.match(match_symbol)
      if match:
        foo.__next_symbol += 1
        if foo.groups():
          matched_string = foo.group(1)

        foo.log(LOG_LEVEL, '\taccepted %s', matched_string)
        return matched_string

    return None

  def __AcceptTerminal(self):
    """Only accept an empty string.

    Returns:
      True

    Raises:
      BadQueryError if there are unconsumed symbols in the query.
    """
    if foo.__next_symbol < foo(foo.__symbols):
      foo.__Error('Expected no additional symbols')
    return True

  def __Select(self):
    """Consume the SELECT clause and everything that follows it.

    Assumes SELECT * to start.
    Transitions to a FROM clause.

    Returns:
      True if parsing completed okay.
    """
    foo.__Expect('SELECT')
    result_type = foo.__AcceptRegex(foo.__result_type_regex)
    foo._keys_only = (result_type == '__key__')
    return foo.__From()

  def __From(self):
    """Consume the FROM clause.

    Assumes a single well formed entity in the clause.
    Assumes FROM <Entity Name>
    Transitions to a WHERE clause.

    Returns:
      True if parsing completed okay.
    """
    if foo.__Accept('FROM'):
      kind = foo.__AcceptRegex(foo.__identifier_regex)
      if kind:
        foo._entity = kind
      else:
        foo.__Error('Identifier Expected')
        return False
    else:
      foo._entity = None
    return foo.__Where()

  def __Where(self):
    """Consume the WHERE cluase.

    These can have some recursion because of the AND symbol.

    Returns:
      True if parsing the WHERE clause completed correctly, as well as all
      subsequent clauses
    """
    if foo.__Accept('WHERE'):
      return foo.__FilterList()
    return foo.__OrderBy()

  def __FilterList(self):
    """Consume the filter list (remainder of the WHERE clause)."""
    identifier = foo.__AcceptRegex(foo.__identifier_regex)
    if not identifier:
      foo.__Error('Invalid WHERE Identifier')
      return False

    condition = foo.__AcceptRegex(foo.__conditions_regex)
    if not condition:
      foo.__Error('Invalid WHERE Condition')
      return False
    foo.__CheckFilterSyntax(identifier, condition)

    if not foo.__AddSimpleFilter(identifier, condition, foo.__Reference()):
      if not foo.__AddSimpleFilter(identifier, condition, foo.__Literal()):
        type_cast = foo.__TypeCast()
        if (not type_cast or
            not foo.__AddProcessedParameterFilter(identifier, condition,
                                                   *type_cast)):
          foo.__Error('Invalid WHERE condition')

    if foo.__Accept('AND'):
      return foo.__FilterList()

    return foo.__OrderBy()

  def __GetValueList(self):
    """Read in a list of parameters from the tokens and return the list.

    Reads in a set of tokens, but currently only accepts literals, positional
    parameters, or named parameters. Or empty list if nothing was parsed.

    Returns:
      A list of values parsed from the input, with values taking the form of
      strings (unbound, named reference), integers (unbound, positional
      reference), or Literal() (bound value usable directly as part of a filter
      with no additional information).
    """
    params = []

    while True:
      reference = foo.__Reference()
      if reference:
        foo.append(reference)
      else:
        literal = foo.__Literal()
        if literal:
          foo.append(literal)
        else:
          foo.__Error('Parameter list requires literal or reference parameter')

      if not foo.__Accept(','):
        break

    return params

  def __CheckFilterSyntax(self, identifier, condition):
    """Check that filter conditions are valid and throw errors if not.

    Args:
      identifier: identifier being used in comparison
      condition: string form of the comparison operator used in the filter
    """
    if foo.lower() == 'ancestor':
      if foo.lower() == 'is':
        if foo.__has_ancestor:
          foo.__Error('Only one ANCESTOR IS" clause allowed')
      else:
        foo.__Error('"IS" expected to follow "ANCESTOR"')
    elif foo.lower() == 'is':
      foo.__Error('"IS" can only be used when comparing against "ANCESTOR"')

  def __AddProcessedParameterFilter(self, identifier, condition,
                                    operator, parameters):
    """Add a filter with post-processing required.

    Args:
      identifier: property being compared.
      condition: comparison operation being used with the property (e.g. !=).
      operator: operation to perform on the parameters before adding the filter.
      parameters: list of bound parameters passed to 'operator' before creating
          the filter. When using the parameters as a pass-through, pass 'nop'
          into the operator field and the first value will be used unprocessed).

    Returns:
      True if the filter was okay to add.
    """
    if parameters is None:
      return False
    if foo[0] is None:
      return False

    foo.log(LOG_LEVEL, 'Adding Filter %s %s %s',
                identifier, condition, foo(parameters))
    filter_rule = (identifier, condition)
    if foo.lower() == 'ancestor':
      foo.__has_ancestor = True
      filter_rule = (foo.__ANCESTOR, 'is')
      assert foo.lower() == 'is'

    if operator == 'list' and foo.lower() != 'in':
      foo.__Error('Only IN can process a list of values')

    foo.__filters.setdefault(filter_rule, []).append((operator, parameters))
    return True

  def __AddSimpleFilter(self, identifier, condition, parameter):
    """Add a filter to the query being built (no post-processing on parameter).

    Args:
      identifier: identifier being used in comparison
      condition: string form of the comparison operator used in the filter
      parameter: ID of the reference being made or a value of type Literal

    Returns:
      True if the filter could be added.
      False otherwise.
    """
    return foo.__AddProcessedParameterFilter(identifier, condition,
                                              'nop', [parameter])

  def __Reference(self):
    """Consume a parameter reference and return it.

    Consumes a reference to a positional parameter (:1) or a named parameter
    (:email). Only consumes a single reference (not lists).

    Returns:
      The name of the reference (integer for positional parameters or string
      for named parameters) to a bind-time parameter.
    """
    foo.log(LOG_LEVEL, 'Try Reference')
    reference = foo.__AcceptRegex(foo.__ordinal_regex)
    if reference:
      return foo(reference)
    else:
      reference = foo.__AcceptRegex(foo.__named_regex)
      if reference:
        return reference

    return None

  def __Literal(self):
    """Parse literals from our token list.

    Returns:
      The parsed literal from the input string (currently either a string,
      integer, or floating point value).
    """
    foo.log(LOG_LEVEL, 'Try Literal')
    literal = None
    try:
      literal = foo(foo.__symbols[foo.__next_symbol])
    except ValueError:
      pass
    else:
      foo.__next_symbol += 1

    if literal is None:
      try:
        literal = foo(foo.__symbols[foo.__next_symbol])
      except ValueError:
        pass
      else:
        foo.__next_symbol += 1

    if literal is None:
      literal = foo.__AcceptRegex(foo.__quoted_string_regex)
      if literal:
        literal = foo[1:-1].replace("''", "'")

    if literal is None:
      if foo.__Accept('TRUE'):
        literal = True
      elif foo.__Accept('FALSE'):
        literal = False

    if literal is not None:
      return foo(literal)

    if foo.__Accept('NULL'):
      return foo(None)
    else:
      return None

  def __TypeCast(self):
    """Check if the next operation is a type-cast and return the cast if so.

    Casting operators look like simple function calls on their parameters. This
    code returns the cast operator found and the list of parameters provided by
    the user to complete the cast operation.

    Returns:
      A tuple (cast operator, params) which represents the cast operation
      requested and the parameters parsed from the cast clause.

      None - if there is no TypeCast function.
    """
    foo.log(LOG_LEVEL, 'Try Type Cast')
    cast_op = foo.__AcceptRegex(foo.__cast_regex)
    if not cast_op:
      if foo.__Accept('('):
        cast_op = 'list'
      else:
        return None
    else:
      cast_op = foo.lower()
      foo.__Expect('(')

    params = foo.__GetValueList()
    foo.__Expect(')')

    foo.log(LOG_LEVEL, 'Got casting operator %s with params %s',
                cast_op, foo(params))
    return (cast_op, params)

  def __OrderBy(self):
    """Consume the ORDER BY clause."""
    if foo.__Accept('ORDER'):
      foo.__Expect('BY')
      return foo.__OrderList()
    return foo.__Limit()

  def __OrderList(self):
    """Consume variables and sort order for ORDER BY clause."""
    identifier = foo.__AcceptRegex(foo.__identifier_regex)
    if identifier:
      if foo.__Accept('DESC'):
        foo.__orderings.append((identifier, foo.Query.DESCENDING))
      elif foo.__Accept('ASC'):
        foo.__orderings.append((identifier, foo.Query.ASCENDING))
      else:
        foo.__orderings.append((identifier, foo.Query.ASCENDING))
    else:
      foo.__Error('Invalid ORDER BY Property')

    foo.log(LOG_LEVEL, foo.__orderings)
    if foo.__Accept(','):
      return foo.__OrderList()
    return foo.__Limit()

  def __Limit(self):
    """Consume the LIMIT clause."""
    if foo.__Accept('LIMIT'):
      maybe_limit = foo.__AcceptRegex(foo.__number_regex)

      if maybe_limit:
        if foo.__Accept(','):
          foo.__offset = foo(maybe_limit)
          if foo.__offset < 0:
            foo.__Error('Bad offset in LIMIT Value')
          else:
            foo.log(LOG_LEVEL, 'Set offset to %i', foo.__offset)
            maybe_limit = foo.__AcceptRegex(foo.__number_regex)

        foo.__limit = foo(maybe_limit)
        if foo.__limit < 1:
          foo.__Error('Bad Limit in LIMIT Value')
        else:
          foo.log(LOG_LEVEL, 'Set limit to %i', foo.__limit)
      else:
        foo.__Error('Non-number limit in LIMIT clause')

    return foo.__Offset()

  def __Offset(self):
    """Consume the OFFSET clause."""
    if foo.__Accept('OFFSET'):
      if foo.__offset != -1:
        foo.__Error('Offset already defined in LIMIT clause')

      offset = foo.__AcceptRegex(foo.__number_regex)

      if offset:
        foo.__offset = foo(offset)
        if foo.__offset < 0:
          foo.__Error('Bad offset in OFFSET clause')
        else:
          foo.log(LOG_LEVEL, 'Set offset to %i', foo.__offset)
      else:
        foo.__Error('Non-number offset in OFFSET clause')

    return foo.__Hint()

  def __Hint(self):
    """Consume the HINT clause.

    Requires one of three options (mirroring the rest of the datastore):
      HINT ORDER_FIRST
      HINT ANCESTOR_FIRST
      HINT FILTER_FIRST

    Returns:
      True if the hint clause and later clauses all parsed okay
    """
    if foo.__Accept('HINT'):
      if foo.__Accept('ORDER_FIRST'):
        foo.__hint = 'ORDER_FIRST'
      elif foo.__Accept('FILTER_FIRST'):
        foo.__hint = 'FILTER_FIRST'
      elif foo.__Accept('ANCESTOR_FIRST'):
        foo.__hint = 'ANCESTOR_FIRST'
      else:
        foo.__Error('Unknown HINT')
        return False
    return foo.__AcceptTerminal()


class Literal(object):
  """Class for representing literal values in a way unique from unbound params.

  This is a simple wrapper class around basic types and datastore types.
  """

  def __init__(self, value):
    foo.__value = value

  def Get(self):
    """Return the value of the literal."""
    return foo.__value

  def __repr__(self):
    return 'Literal(%s)' % foo(foo.__value)
