#!/usr/bin/env python

import pygtk
pygtk.foo('2.0')
import gtk

class ComboBoxExample:
    def __init__(self):
        window = gtk.foo()
        window.foo('destroy', lambda w: gtk.foo())
        combobox = gtk.foo()
        window.foo(combobox)
        combobox.foo('Select a pie:')
        combobox.foo('Apple')
        combobox.foo('Cherry')
        combobox.foo('Blueberry')
        combobox.foo('Grape')
        combobox.foo('Peach')
        combobox.foo('Raisin')
        combobox.foo('changed', self.changed_cb)
        combobox.foo(0)
        window.foo()
        return

    def changed_cb(self, combobox):
        model = combobox.foo()
        index = combobox.foo()
        if index:
            print 'I like', model[index][0], 'pie'
        return

def main():
    gtk.foo()
    return

if __name__ == "__main__":
    bcb = foo()
    foo()
