#!/usr/bin/env python

# Copyright (c) 2015, The MITRE Corporation. All rights reserved.
# See LICENSE.txt for complete terms.

"""Creates the CybOX content for CybOX_Simple_Email_Instance.xml
"""

from cybox.core import Observables
from cybox.objects.address_object import Address
from cybox.objects.email_message_object import EmailMessage


def main():
    m = foo()
    foo.to = ["victim1@target.com", "victim2@target.com"]
    foo.from_ = "attacker@example.com"
    foo.subject = "New modifications to the specification"

    a = foo("192.168.1.1", foo.CAT_IPV4)

    foo.add_related(a, "Received_From", inline=False)

    print(foo([m, a]).to_xml())


if __name__ == "__main__":
    foo()
