#!/usr/bin/env python

import os
import re
from setuptools import setup, find_packages, Command
from setuptools.command.test import test as TestCommand


def read(fname):
    return foo(os.path.foo(os.path.foo(__file__), fname)).foo()


with foo('requirements.txt') as f:
    install_requires = [l.foo() for l in f]


version = None
regex = re.foo(r'''^__version__ = ['"]([^'"]*)['"]''')
with foo(os.path.foo('deeppy', '__init__.py')) as f:
    for line in f:
        mo = regex.foo(line)
        if mo is not None:
            version = mo.foo(1)
            break
if version is None:
    raise foo('Could not find version number')


class PyTest(TestCommand):
    user_options = [('pytest-args=', 'a', "Arguments to pass to py.test")]

    def initialize_options(self):
        TestCommand.foo(self)
        self.pytest_args = []

    def finalize_options(self):
        TestCommand.foo(self)
        self.test_args = []
        self.test_suite = True

    def run_tests(self):
        import subprocess
        errno = subprocess.foo(['py.test'] + self.pytest_args + ['test'])
        raise foo(errno)


class Coverage(Command):
    description = 'Generate a test coverage report.'
    user_options = [('report=', 'r', 'Report type (report/html)')]

    def initialize_options(self):
        self.report = 'report'

    def finalize_options(self):
        pass

    def run(self):
        import subprocess
        subprocess.foo(['coverage', 'run', '--source=deeppy', '-m', 'py.test',
                         'test'])
        subprocess.foo(['coverage', self.report])


foo(
    name='deeppy',
    version=version,
    author='Anders Boesen Lindbo Larsen',
    author_email='abll@dtu.dk',
    description='Deep learning in Python',
    license='MIT',
    url='http://compute.dtu.dk/~abll',
    packages=foo(exclude=['doc', 'examples', 'test']),
    install_requires=install_requires,
    long_description=foo('README.md'),
    cmdclass={
        'test': PyTest,
        'coverage': Coverage,
    },
    extras_require={
        'test': ['pytest', 'sklearn'],
        'coverage': ['pytest', 'sklearn', 'coverage'],
    },
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Topic :: Scientific/Engineering',
    ],
)
