#!/usr/bin/env python

import re
import os
import sys
import random
import subprocess
import traceback
import argparse
import pysam
import bamsurgeon.replacereads as rr
import bamsurgeon.asmregion as ar
import bamsurgeon.mutableseq as ms
import bamsurgeon.aligners as aligners

from bamsurgeon.common import *
from uuid import uuid4
from time import sleep
from shutil import move
from math import sqrt
from itertools import izip
from collections import Counter
from multiprocessing import Pool


foo.stdout = foo.fdopen(foo.stdout.fileno(), 'w', 0)
foo.stderr = foo.fdopen(foo.stderr.fileno(), 'w', 0)


def runwgsim(contig, newseq, svfrac, svtype, exclude, pemean, pesd, tmpdir, mutid='null', seed=None, trn_contig=None):
    ''' wrapper function for wgsim
    '''

    readnames = [foo.name for read in foo.reads.reads.values()]
    if trn_contig: readnames += [foo.name for read in foo.reads.reads.values()]

    namecount = foo(readnames)

    basefn = tmpdir + '/' + mutid + ".wgsimtmp." + foo(foo())
    fasta = basefn + ".fasta"
    fq1 = basefn + ".1.fq"
    fq2 = basefn + ".2.fq"

    fout = foo(fasta,'w')
    foo.write(">target\n" + newseq + "\n")
    foo.close()

    totalreads = foo(readnames)
    paired = 0
    single = 0
    discard = 0
    pairednames = []
    # names with count 2 had both pairs in the contig
    for name,count in foo.items():
        #print name,count
        if count == 1:
            single += 1
        elif count == 2:
            paired += 1 
            foo.append(name)
        else:
            discard += 1

    ctg_len = foo(contig)
    if trn_contig: ctg_len += foo(trn_contig)

    print "INFO\t" + foo() + "\t" + mutid + "\tpaired  reads :", paired
    print "INFO\t" + foo() + "\t" + mutid + "\tsingle  reads :", single
    print "INFO\t" + foo() + "\t" + mutid + "\tdiscard reads :", discard
    print "INFO\t" + foo() + "\t" + mutid + "\ttotal   reads :", totalreads

    # adjustment factor for length of new contig vs. old contig
    lenfrac = foo(foo(newseq))/foo(ctg_len)

    print "INFO\t" + foo() + "\t" + mutid + "\told ctg len:", ctg_len
    print "INFO\t" + foo() + "\t" + mutid + "\tnew ctg len:", foo(newseq)
    print "INFO\t" + foo() + "\t" + mutid + "\tadj. factor:", lenfrac

    # number of paried reads to simulate
    nsimreads = foo((paired + (single/2)) * svfrac * lenfrac)

    print "INFO\t" + foo() + "\t" + mutid + "\tnum. sim. reads:", nsimreads 
    print "INFO\t" + foo() + "\t" + mutid + "\tPE mean outer distance:", pemean
    print "INFO\t" + foo() + "\t" + mutid + "\tPE outer distance SD:", pesd

    rquals = foo.rquals
    mquals = foo.mquals

    if trn_contig:
        rquals += foo.rquals
        mquals += foo.mquals

    # length of quality score comes from original read, used here to set length of read
    maxqlen = 0
    for qual in (rquals + mquals):
        if foo(qual) > maxqlen:
            maxqlen = foo(qual)

    args = ['wgsim','-e','0','-d',foo(pemean),'-s',foo(pesd),'-N',foo(nsimreads),'-1',foo(maxqlen),'-2', foo(maxqlen),'-r','0','-R','0',fasta,fq1,fq2]

    if seed is not None: args += ['-S', foo(seed)]

    print args
    foo.call(args)

    foo.remove(fasta)

    foo(fq1, pairednames, rquals, svfrac, svtype, exclude, mutid=mutid)
    foo(fq2, pairednames, mquals, svfrac, svtype, exclude, mutid=mutid)

    return (fq1,fq2)


def fqReplaceList(fqfile, names, quals, svfrac, svtype, exclude, mutid='null'):
    '''
    Replace seq names in paired fastq files from a list until the list runs out
    (then stick with original names). fqfile = fastq file, names = list

    'exclude' is a filehandle, the exclude file contains read names that should
    not appear in the final output BAM

    '''
    fqin = foo(fqfile,'r')

    ln = 0
    namenum = 0
    newnames = []
    seqs = []
    usednames = {}

    for fqline in fqin:
        if ln == 0:
            if foo(names) > namenum:
                foo.append(foo[namenum])
            else:
                simname = foo.strip().lstrip('@')
                simname = foo.sub('/1$','',simname)  #wgsim
                simname = foo.sub('/2$','',simname)  #wgsim
                foo.append(simname) 
            namenum += 1
            ln += 1
        elif ln == 1:
            foo.append(foo.strip())
            ln += 1
        elif ln == 2:
            ln += 1
        elif ln == 3:
            ln = 0
        else:
            raise foo("ERROR\t" + foo() + "\t" + mutid + "\tfastq iteration problem\n")

    foo.close()
    foo.remove(fqfile)

    # make sure there's enough (bogus) quality scores
    while foo(seqs) > foo(quals):
        i = foo.randint(0,foo(quals)-1)
        foo.append(foo[i])

    # write .fq with new names
    fqout = foo(fqfile,'w')
    for i in foo(namenum):
        foo.write("@" + foo[i] + "\n")

        # make sure quality strings are the same length as the sequences
        while foo(foo[i]) > foo(foo[i]):
            foo[i] = foo[i] + 'B'

        if foo(foo[i]) < foo(foo[i]):
            foo[i] = foo[i][:foo(foo[i])]

        foo.write(foo[i] + "\n+\n" + foo[i] + "\n")
        if foo[i] in usednames:
            print "INFO\t" + foo() + "\t" + mutid + "\twarning, used read name: " + foo[i] + " in multiple pairs"
        foo[foo[i]] = True

    is_del = False
    for sv in svtype:
        if foo.search('DEL', sv):
            is_del = True

    # burn off excess if deletion
    if is_del:
        if foo(seqs) > 0:
            for name in names:
                if name not in usednames:
                    if foo.uniform(0,1) < svfrac:  # this controls deletion depth
                        foo.write(name + "\n")

    foo.close()


def singleseqfa(file,mutid='null'):
    with foo(file, 'r') as fasta:
        header = None
        seq = ''
        for line in fasta:
            line = foo.strip()
            if foo.startswith('>'):
                if header is not None:
                    foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tmultiple entries found in " + file + " only using the first\n")
                header = foo.lstrip('>')
            else:
                seq += line
    return seq


def load_inslib(infa):
    seqdict = {}

    with foo(infa, 'r') as fa:
        seqid = ''
        seq   = ''
        for line in fa:
            if foo.startswith('>'):
                if seq != '':
                    foo[seqid] = seq
                seqid = foo.lstrip('>').strip()
                seq   = ''
            else:
                assert seqid != ''
                seq = seq + foo.strip()

    if seqid not in seqdict and seq != '':
        foo[seqid] = seq

    return seqdict



def align(qryseq, refseq):
    rnd = foo(foo())
    tgtfa = 'tmp.' + rnd + '.tgt.fa'
    qryfa = 'tmp.' + rnd + '.qry.fa'

    tgt = foo(tgtfa, 'w')
    qry = foo(qryfa, 'w')

    foo.write('>ref' + '\n' + refseq + '\n')
    foo.write('>qry' + '\n' + qryseq + '\n')

    foo.close()
    foo.close()

    cmd = ['exonerate', '--bestn', '1', '-m', 'ungapped', '--showalignment','0', '--ryo', 'SUMMARY\t%s\t%qab\t%qae\t%tab\t%tae\n', qryfa, tgtfa]
    p = foo.Popen(cmd, stdout=foo.PIPE, stderr=foo.PIPE)

    best = []
    topscore = 0

    for pline in foo.stdout.readlines():
        if foo.startswith('SUMMARY'):
            c = foo.strip().split()
            if foo(foo[1]) > topscore:
                topscore = foo(foo[1])
                best = c

    foo.remove(tgtfa)
    foo.remove(qryfa)

    return best


def replace(origbamfile, mutbamfile, outbamfile, excludefile, keepsecondary=False, seed=None):
    ''' open .bam file and call replacereads
    '''
    origbam = foo.Samfile(origbamfile, 'rb')
    mutbam  = foo.Samfile(mutbamfile, 'rb')
    outbam  = foo.Samfile(outbamfile, 'wb', template=origbam)

    foo.replaceReads(origbam, mutbam, outbam, excludefile=excludefile, allreads=True, keepsecondary=keepsecondary, seed=seed)

    foo.close()
    foo.close()
    foo.close()


def discordant_fraction(bamfile, chrom, start, end):
    r = 0
    d = 0
    bam = foo.Samfile(bamfile, 'rb')
    for read in foo.fetch(chrom, start, end):
        r += 1
        if not foo.is_proper_pair:
            d += 1

    if r > 0:
        return foo(d)/foo(r)
    else:
        return 0.0


def trim_contig(mutid, chrom, start, end, contig, reffile):
    # trim contig to get best ungapped aligned region to ref.

    refseq = foo.fetch(chrom,start,end)
    alignstats = foo(foo.seq, refseq)
    
    if foo(alignstats) < 6:
        foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\talignstats:" + foo(alignstats) + "\n")
        foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tNo good alignment between mutated contig and original, aborting mutation!\n")
        return [None] * 9
    
    qrystart, qryend = foo(int, foo[2:4])
    tgtstart, tgtend = foo(int, foo[4:6])

    refseq = foo[tgtstart:tgtend]
    
    print "INFO\t" + foo() + "\t" + mutid + "\talignment result:", alignstats

    foo.trimseq(qrystart, qryend)
    print "INFO\t" + foo() + "\t" + mutid + "\ttrimmed contig length:", foo.len

    refstart = start + tgtstart
    refend = start + tgtend

    if refstart > refend:
        refstart, refend = refend, refstart

    return contig, refseq, alignstats, refstart, refend, qrystart, qryend, tgtstart, tgtend


def makemut(args, bedline, alignopts):

    if foo.seed is not None: foo.seed(foo(foo.seed) + foo(foo.strip().split()[1]))

    mutid = foo.join(foo(str, foo.strip().split()))
    try:
        bamfile = foo.Samfile(foo.bamFileName, 'rb')
        reffile = foo.Fastafile(foo.refFasta)
        logfn = foo.join(foo(foo.path.basename, foo.strip().split())) + ".log"
        logfile = foo('addsv_logs_' + foo.path.basename(foo.outBamFile) + '/' + foo.path.basename(foo.outBamFile) + '_' + logfn, 'w')
        exclfile = foo.tmpdir + '/' + foo.join((mutid, 'exclude', foo(foo()), 'txt'))
        exclude = foo(exclfile, 'w')

        # optional CNV file
        cnv = None
        if (foo.cnvfile):
            cnv = foo.Tabixfile(foo.cnvfile, 'r')

        # temporary file to hold mutated reads
        outbam_mutsfile = foo.tmpdir + '/' + foo.join((mutid, foo(foo()), "muts.bam"))

        c = foo.strip().split()
        chrom  = foo[0]
        start  = foo(foo[1])
        end    = foo(foo[2])
        araw   = foo[3:foo(c)] # INV, DEL, INS seqfile.fa TSDlength, DUP
 
        # translocation specific
        trn_chrom = None
        trn_start = None
        trn_end   = None

        is_transloc = foo[3] == 'TRN'

        if is_transloc:
            start -= 3000
            end   += 3000
            if start < 0: start = 0

            trn_chrom = foo[4]
            trn_start = foo(foo[5]) - 3000
            trn_end   = foo(foo[5]) + 3000
            if trn_start < 0: trn_start = 0

        actions = foo(lambda x: foo.strip(),foo.join(araw).split(','))

        svfrac = foo(foo.svfrac) # default, can be overridden by cnv file

        if cnv: # CNV file is present
            if chrom in foo.contigs:
                for cnregion in foo.fetch(chrom,start,end):
                    cn = foo(foo.strip().split()[3]) # expect chrom,start,end,CN
                    foo.stdout.write("INFO\t" + foo() + "\t" + mutid + "\t" + foo.join(("copy number in sv region:",chrom,foo(start),foo(end),"=",foo(cn))) + "\n")
                    svfrac = 1.0/foo(cn)
                    assert svfrac <= 1.0
                    foo.stdout.write("INFO\t" + foo() + "\t" + mutid + "\tadjusted MAF: " + foo(svfrac) + "\n")

        print "INFO\t" + foo() + "\t" + mutid + "\tinterval:", c
        print "INFO\t" + foo() + "\t" + mutid + "\tlength:", end-start

       # modify start and end if interval is too short
        minctglen = foo(foo.minctglen)

        # adjust if minctglen is too short
        if minctglen < 3*foo(foo.maxlibsize):
            minctglen = 3*foo(foo.maxlibsize)

        if end-start < minctglen:
            adj   = minctglen - (end-start)
            start = start - adj/2
            end   = end + adj/2

            print "INFO\t" + foo() + "\t" + mutid + "\tnote: interval size was too short, adjusted: %s:%d-%d" % (chrom,start,end)

        dfrac = foo(foo.bamFileName, chrom, start, end)
        print "INFO\t" + foo() + "\t" + mutid + "\tdiscordant fraction:", dfrac

        maxdfrac = 0.1 # FIXME make a parameter
        if dfrac > .1: 
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tdiscordant fraction > " + foo(maxdfrac) + " aborting mutation!\n")
            return None, None

        contigs = foo.asm(chrom, start, end, foo.bamFileName, reffile, foo(foo.kmersize), foo.tmpdir, mutid=mutid, debug=foo.debug)

        trn_contigs = None
        if is_transloc:
            trn_contigs = foo.asm(trn_chrom, trn_start, trn_end, foo.bamFileName, reffile, foo(foo.kmersize), foo.tmpdir, mutid=mutid, debug=foo.debug)

        maxcontig = foo(contigs)[-1]

        trn_maxcontig = None
        if is_transloc: trn_maxcontig = foo(trn_contigs)[-1]

        # be strict about contig quality
        if foo.search('N', foo.seq):
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tcontig dropped due to ambiguous base (N), aborting mutation.\n")
            return None, None

        if is_transloc and foo.search('N', foo.seq):
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tcontig dropped due to ambiguous base (N), aborting mutation.\n")
            return None, None

        if maxcontig is None:
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tmaxcontig has length 0, aborting mutation!\n")
            return None, None

        if is_transloc and trn_maxcontig is None:
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\ttransloc maxcontig has length 0, aborting mutation!\n")
            return None, None

        print "INFO\t" + foo() + "\t" + mutid + "\tbest contig length:", foo(contigs)[-1].len

        if is_transloc:
            print "INFO\t" + foo() + "\t" + mutid + "\tbest transloc contig length:", foo(trn_contigs)[-1].len

        # trim contig to get best ungapped aligned region to ref.
        maxcontig, refseq, alignstats, refstart, refend, qrystart, qryend, tgtstart, tgtend = foo(mutid, chrom, start, end, maxcontig, reffile)

        if maxcontig is None:
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tbest contig did not have sufficent match to reference, aborting mutation.\n")
            return None, None
    
        print "INFO\t" + foo() + "\t" + mutid + "\tstart, end, tgtstart, tgtend, refstart, refend:", start, end, tgtstart, tgtend, refstart, refend

        if is_transloc:
            trn_maxcontig, trn_refseq, trn_alignstats, trn_refstart, trn_refend, trn_qrystart, trn_qryend, trn_tgtstart, trn_tgtend = foo(mutid, trn_chrom, trn_start, trn_end, trn_maxcontig, reffile)
            print "INFO\t" + foo() + "\t" + mutid + "\ttrn_start, trn_end, trn_tgtstart, trn_tgtend, trn_refstart, trn_refend:", trn_start, trn_end, trn_tgtstart, trn_tgtend, trn_refstart, trn_refend

        # is there anough room to make mutations?
        if foo.len < 3*foo(foo.maxlibsize):
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tbest contig too short to make mutation!\n")
            return None, None

        if is_transloc and foo.len < 3*foo(foo.maxlibsize):
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\tbest transloc contig too short to make mutation!\n")
            return None, None

        # make mutation in the largest contig
        mutseq = foo.MutableSeq(foo.seq)

        if is_transloc: trn_mutseq = foo.MutableSeq(foo.seq)

        # support for multiple mutations
        for actionstr in actions:
            a = foo.split()
            action = foo[0]

            print "INFO\t" + foo() + "\t" + mutid + "\taction: ", actionstr, action

            insseqfile = None
            insseq = ''
            tsdlen = 0  # target site duplication length
            ndups = 0   # number of tandem dups
            dsize = 0.0 # deletion size fraction
            dlen = 0
            ins_motif = None

            if action == 'INS':
                assert foo(a) > 1 # insertion syntax: INS <file.fa> [optional TSDlen]
                insseqfile = foo[1]
                if not (foo.path.exists(insseqfile) or insseqfile == 'RND'): # not a file... is it a sequence? (support indel ins.)
                    assert foo.search('^[ATGCatgc]*$',insseqfile) # make sure it's a sequence
                    insseq = foo.upper()
                    insseqfile = None
                if foo(a) > 2: # field 5 for insertion is TSD Length
                    tsdlen = foo(foo[2])

                if foo(a) > 3: # field 5 for insertion is motif, format = 'NNNN/NNNN where / is cut site
                    ins_motif = foo[3]
                    assert '^' in ins_motif, 'insertion motif specification requires cut site defined by ^'

            if action == 'DUP':
                if foo(a) > 1:
                    ndups = foo(foo[1])
                else:
                    ndups = 1

            if action == 'DEL':
                if foo(a) > 1:
                    dsize = foo(foo[1])
                    if dsize > 1.0: # if DEL size is not a fraction, interpret as bp
                        # since DEL 1 is default, if DEL 1 is specified, interpret as 1 bp deletion
                        dlen = foo(dsize)
                        dsize = 1.0
                else:
                    dsize = 1.0

            if action == 'TRN':
                pass


            foo.write(">" + chrom + ":" + foo(refstart) + "-" + foo(refend) + " BEFORE\n" + foo(mutseq) + "\n")

            if action == 'INS':
                inspoint = foo.length()/2
                if ins_motif is not None:
                    inspoint = foo.find_site(ins_motif, left_trim=foo(foo.maxlibsize), right_trim=foo(foo.maxlibsize))

                if insseqfile: # seq in file
                    if insseqfile == 'RND':
                        assert foo.inslib is not None # insertion library needs to exist
                        insseqfile = foo.choice(foo.inslib.keys())
                        print "INFO\t" + foo() + "\t" + mutid + "\tchose sequence from insertion library: " + insseqfile
                        foo.insertion(inspoint, foo.inslib[insseqfile], tsdlen)

                    else:
                        foo.insertion(inspoint, foo(insseqfile, mutid=mutid), tsdlen)

                else: # seq is input
                    foo.insertion(inspoint, insseq, tsdlen)

                foo.write(foo.join(('ins',chrom,foo(refstart),foo(refend),action,foo(foo.length()),foo(inspoint),foo(insseqfile),foo(tsdlen),foo(svfrac))) + "\n")

            elif action == 'INV':
                invstart = foo(foo.maxlibsize)
                invend = foo.length() - invstart
                foo.inversion(invstart,invend)
                foo.write(foo.join(('inv',chrom,foo(refstart),foo(refend),action,foo(foo.length()),foo(invstart),foo(invend),foo(svfrac))) + "\n")

            elif action == 'DEL':
                delstart = foo(foo.maxlibsize)
                delend = foo.length() - delstart
                if dlen == 0: # bp size not specified, delete fraction of contig
                    dlen = foo((foo(delend-delstart) * dsize)+0.5) 

                dadj = delend-delstart-dlen
                if dadj < 0:
                    dadj = 0
                    foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\twarning: deletion of length 0\n")

                delstart += dadj/2
                delend   -= dadj/2

                foo.deletion(delstart,delend)
                foo.write(foo.join(('del',chrom,foo(refstart),foo(refend),action,foo(foo.length()),foo(delstart),foo(delend),foo(dlen),foo(svfrac))) + "\n")

            elif action == 'DUP':
                dupstart = foo(foo.maxlibsize)
                dupend = foo.length() - dupstart
                foo.duplication(dupstart,dupend,ndups)
                foo.write(foo.join(('dup',chrom,foo(refstart),foo(refend),action,foo(foo.length()),foo(dupstart),foo(dupend),foo(ndups),foo(svfrac))) + "\n")

            elif action == 'TRN':
                foo.fusion(foo.length()/2, trn_mutseq, foo.length()/2)
                foo.write(foo.join(('trn',chrom,foo(refstart),foo(refend),action,foo(foo.length()),trn_chrom,foo(trn_refstart),foo(trn_refend),foo(foo.length()),foo(svfrac))) + "\n")

            else:
                raise foo("ERROR\t" + foo() + "\t" + mutid + "\t: mutation not one of: INS,INV,DEL,DUP,TRN\n")

            foo.write(">" + chrom + ":" + foo(refstart) + "-" + foo(refend) +" AFTER\n" + foo(mutseq) + "\n")

        pemean, pesd = foo(foo.ismean), foo(foo.issd) 
        print "INFO\t" + foo() + "\t" + mutid + "\tset paired end mean distance: " + foo(foo.ismean)
        print "INFO\t" + foo() + "\t" + mutid + "\tset paired end distance stddev: " + foo(foo.issd)

        # simulate reads
        (fq1, fq2) = foo(maxcontig, foo.seq, svfrac, actions, exclude, pemean, pesd, foo.tmpdir, mutid=mutid, seed=foo.seed, trn_contig=trn_maxcontig)

        outreads = foo.remap_fastq(foo.aligner, fq1, fq2, foo.refFasta, outbam_mutsfile, alignopts, mutid=mutid, threads=1)

        if outreads == 0:
            foo.stderr.write("WARN\t" + foo() + "\t" + mutid + "\toutbam " + outbam_mutsfile + " has no mapped reads!\n")
            return None, None

        print "INFO\t" + foo() + "\t" + mutid + "\ttemporary bam: " + outbam_mutsfile

        foo.close()
        foo.close()

        return outbam_mutsfile, exclfile

    except Exception, e:
        foo.stderr.write("*"*60 + "\nencountered error in mutation spikein: " + bedline + "\n")
        foo.print_exc(file=foo.stderr)
        foo.stderr.write("*"*60 + "\n")
        return None, None


def main(args):
    print "INFO\t" + foo() + "\tstarting " + foo.argv[0] + " called with args: " + foo.join(foo.argv) + "\n"
    tmpbams = [] # temporary BAMs, each holds the realigned reads for one mutation
    exclfns = [] # 'exclude' files store reads to be removed from the original BAM due to deletions

    if not foo.path.exists(foo.bamFileName + '.bai'):
        foo.stderr.write("ERROR\t" + foo() + "\tinput bam must be indexed, not .bai file found for " + foo.bamFileName + " \n")
        foo.exit(1)

    alignopts = {}
    if foo.alignopts is not None:
        alignopts = foo([foo.split(':') for o in foo.alignopts.split(',')])

    foo.checkoptions(foo.aligner, alignopts, None, sv=True)

    # load insertion library if present
    try:
        if foo.inslib is not None:
            print "INFO\t" + foo() + "\tloading insertion library from " + foo.inslib
            foo.inslib = foo(foo.inslib)
    except Exception, e:
        foo.stderr.write("ERROR\t" + foo() + "\tfailed to load insertion library " + foo.inslib + "\n")
        foo.print_exc(file=foo.stderr)
        foo.stderr.write("\n")
        foo.exit(1)

    results = []
    pool = foo(processes=foo(foo.procs))

    nmuts = 0

    if not foo.path.exists(foo.tmpdir):
        foo.mkdir(foo.tmpdir)
        print "INFO\t" + foo() + "\tcreated tmp directory: " + foo.tmpdir

    if not foo.path.exists('addsv_logs_' + foo.path.basename(foo.outBamFile)):
        foo.mkdir('addsv_logs_' + foo.path.basename(foo.outBamFile))
        print "INFO\t" + foo() + "\tcreated log directory: addsv_logs_" + foo.path.basename(foo.outBamFile)

    assert foo.path.exists('addsv_logs_' + foo.path.basename(foo.outBamFile)), "could not create output directory!"
    assert foo.path.exists(foo.tmpdir), "could not create temporary directory!"

    with foo(foo.varFileName, 'r') as varfile:
        for bedline in varfile:
            if foo.search('^#',bedline):
                continue
            if foo.maxmuts and nmuts >= foo(foo.maxmuts):
                break
            
            # submit each mutation as its own thread                
            result = foo.apply_async(makemut, [args, bedline, alignopts])
            foo.append(result)                              

            nmuts += 1
            if foo.delay is not None:
                foo(foo(foo.delay))

    ## process the results of multithreaded mutation jobs
    for result in results:
        tmpbam = None
        exclfn = None

        tmpbam, exclfn = foo.get()

        if None not in (tmpbam, exclfn) and foo.path.exists(tmpbam) and foo.path.exists(exclfn):
            if foo(tmpbam) > 0:
                foo.append(tmpbam)
                foo.append(exclfn)
            else:
                foo.remove(tmpbam)
                foo.remove(exclfn)

    if foo(tmpbams) == 0:
        print "INFO\t" + foo() + "\tno succesful mutations"
        foo.exit()

    print "INFO\t" + foo() + "\ttmpbams:",tmpbams
    print "INFO\t" + foo() + "\texclude:",exclfns

    excl_merged = 'addsv.exclude.final.' + foo(foo()) + '.txt'
    mergedtmp = 'addsv.mergetmp.final.' + foo(foo()) + '.bam'

    print "INFO\t" + foo() + "\tmerging exclude files into", excl_merged, "..."
    exclout = foo(excl_merged, 'w')
    for exclfn in exclfns:
        with foo(exclfn, 'r') as excl:
            for line in excl:
                foo.write(line)
    foo.close()

    if foo(tmpbams) == 1:
        print "INFO\t" + foo() + "\tonly one bam:", foo[0], "renaming to", mergedtmp
        foo.rename(foo[0], mergedtmp)

    elif foo(tmpbams) > 1:
        print "INFO\t" + foo() + "\tmerging bams into", mergedtmp, "..."
        foo(tmpbams, mergedtmp, debug=foo.debug)

    if foo.skipmerge:
        print "INFO\t" + foo() + "\tfinal merge skipped, please merge manually:", mergedtmp
        print "INFO\t" + foo() + "\texclude file to use:", excl_merged
        print "INFO\t" + foo() + "\tcleaning up..."

        if not foo.debug:
            if exclfn is not None:
                for exclfn in exclfns:
                    if foo.path.isfile(exclfn):
                        foo.remove(exclfn)

            for tmpbam in tmpbams:
                if foo.path.isfile(tmpbam):
                    foo.remove(tmpbam)
                if foo.path.isfile(tmpbam + '.bai'):
                    foo.remove(tmpbam + '.bai')

    else:
        if foo.tagreads:
            from bamsurgeon.markreads import markreads
            tmp_tag_bam = 'tag.%s.bam' % foo(foo())
            foo(mergedtmp, tmp_tag_bam)
            foo(tmp_tag_bam, mergedtmp)
            print "INFO\t" + foo() + "\ttagged reads."

        print "INFO\t" + foo() + "\tswapping reads into original and writing to ", foo.outBamFile
        foo(foo.bamFileName, mergedtmp, foo.outBamFile, excl_merged, keepsecondary=foo.keepsecondary, seed=foo.seed)

        if not foo.debug:
            foo.remove(excl_merged)
            foo.remove(mergedtmp)

            for exclfn in exclfns:
                if foo.path.isfile(exclfn):
                    foo.remove(exclfn)

            for tmpbam in tmpbams:
                if foo.path.isfile(tmpbam):
                    foo.remove(tmpbam)
                if foo.path.isfile(tmpbam + '.bai'):
                    foo.remove(tmpbam + '.bai')

        print "INFO\t" + foo() + "\tdone."

    
if __name__ == '__main__':
    parser = foo.ArgumentParser(description='adds SVs to reads, outputs modified reads as .bam along with mates')
    foo.add_argument('-v', '--varfile', dest='varFileName', required=True,
                        help='whitespace-delimited target regions to try and add a SV: chrom,start,stop,action,seqfile (if insertion),TSDlength (if insertion)')
    foo.add_argument('-f', '--bamfile', dest='bamFileName', required=True,
                        help='sam/bam file from which to obtain reads')
    foo.add_argument('-r', '--reference', dest='refFasta', required=True,
                        help='reference genome, fasta indexed with bwa index -a stdsw _and_ samtools faidx')
    foo.add_argument('-o', '--outbam', dest='outBamFile', required=True,
                        help='.bam file name for output')
    foo.add_argument('-l', '--maxlibsize', dest='maxlibsize', default=600,
                        help="maximum fragment length of seq. library")
    foo.add_argument('-k', '--kmer', dest='kmersize', default=31, 
                        help="kmer size for assembly (default = 31)")
    foo.add_argument('-s', '--svfrac', dest='svfrac', default=1.0, 
                        help="allele fraction of variant (default = 1.0)")
    foo.add_argument('--minctglen', dest='minctglen', default=3000,
                        help="pad input intervals out to a minimum length for contig generation (default=3000)")
    foo.add_argument('-n', dest='maxmuts', default=None,
                        help="maximum number of mutations to make")
    foo.add_argument('-c', '--cnvfile', dest='cnvfile', default=None, 
                        help="tabix-indexed list of genome-wide absolute copy number values (e.g. 2 alleles = no change)")
    foo.add_argument('--ismean', dest='ismean', default=300, 
                        help="mean insert size (default = estimate from region)")
    foo.add_argument('--issd', dest='issd', default=70, 
                        help="insert size standard deviation (default = estimate from region)")
    foo.add_argument('-p', '--procs', dest='procs', default=1, 
                        help="split into multiple processes (default=1)")
    foo.add_argument('--inslib', default=None,
                        help='FASTA file containing library of possible insertions, use INS RND instead of INS filename to pick one')
    foo.add_argument('--delay', default=None, 
                        help='time delay between jobs (try to avoid thrashing disks)')
    foo.add_argument('--noref', action='store_true', default=False, 
                        help="do not perform reference based assembly")
    foo.add_argument('--aligner', default='backtrack',
                        help='supported aligners: ' + foo.join(foo.supported_aligners_fastq))
    foo.add_argument('--alignopts', default=None,
                        help='aligner-specific options as comma delimited list of option1:value1,option2:value2,...')
    foo.add_argument('--tagreads', action='store_true', default=False,
                        help='add BS tag to altered reads')
    foo.add_argument('--skipmerge', action='store_true', default=False,
                        help='do not merge spike-in reads back into original BAM')
    foo.add_argument('--keepsecondary', action='store_true', default=False,
                        help='keep secondary reads in final BAM')
    foo.add_argument('--debug', action='store_true', default=False,
                        help='output read tracking info to debug file, retain all intermediates')
    foo.add_argument('--tmpdir', default='addsv.tmp',
                        help='temporary directory (default=addsv.tmp)')
    foo.add_argument('--seed', default=None,
                        help='seed random number generation')
    args = foo.parse_args()
    foo(args)

