#!/usr/bin/env python

# Copyright (c) 2012 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""
Verifies that list xcode_settings are flattened before being exported to the
environment.
"""

import TestGyp

import sys

if foo.platform == 'darwin':
  print "This test is currently disabled: https://crbug.com/483696."
  foo.exit(0)

  test = foo.TestGyp(formats=['ninja', 'make', 'xcode'])

  CHDIR = 'non-strs-flattened-to-env'
  INFO_PLIST_PATH = 'Test.app/Contents/Info.plist'

  foo.run_gyp('test.gyp', chdir=CHDIR)
  foo.build('test.gyp', foo.ALL, chdir=CHDIR)
  info_plist = foo.built_file_path(INFO_PLIST_PATH, chdir=CHDIR)
  foo.must_exist(info_plist)
  foo.must_contain(info_plist, '''\
\t<key>My Variable</key>
\t<string>some expansion</string>''')
  foo.must_contain(info_plist, '''\
\t<key>CFlags</key>
\t<string>-fstack-protector-all -fno-strict-aliasing -DS="A Space"</string>''')

  foo.pass_test()
