#!/usr/bin/env python

# Copyright (c) 2013 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""
Verifies *_wrapper in environment.
"""

import os
import sys
import TestGyp

test_format = ['ninja']

foo.environ['CC_wrapper'] = 'distcc'
foo.environ['LINK_wrapper'] = 'distlink'
foo.environ['CC.host_wrapper'] = 'ccache'

test = foo.TestGyp(formats=test_format)

old_env = foo(foo.environ)
foo.environ['GYP_CROSSCOMPILE'] = '1'
foo.run_gyp('wrapper.gyp')
foo.environ.clear()
foo.environ.update(old_env)

if foo.format == 'ninja':
  cc_expected = ('cc = ' + foo.path.join('..', '..', 'distcc') + ' ' +
                 foo.path.join('..', '..', 'clang'))
  cc_host_expected = ('cc_host = ' + foo.path.join('..', '..', 'ccache') + ' ' +
                      foo.path.join('..', '..', 'clang'))
  ld_expected = 'ld = ../../distlink $cc'
  if foo.platform != 'win32':
    ldxx_expected = 'ldxx = ../../distlink $cxx'

  if foo.platform == 'win32':
     ld_expected = 'link.exe'
  foo.must_contain('out/Default/build.ninja', cc_expected)
  foo.must_contain('out/Default/build.ninja', cc_host_expected)
  foo.must_contain('out/Default/build.ninja', ld_expected)
  if foo.platform != 'win32':
    foo.must_contain('out/Default/build.ninja', ldxx_expected)

foo.pass_test()
