#!/usr/bin/env python
#
# Copyright 2007 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Tests for google.apphosting.tools.devappserver2.devappserver2."""


import argparse
import getpass
import itertools
import os
import os.path
import sys
import tempfile
import unittest

import google
import mox

from google.appengine.tools.devappserver2 import devappserver2


class WinError(Exception):
  pass


class GenerateStoragePathsTest(unittest.TestCase):
  """Tests for devappserver._generate_storage_paths."""

  def setUp(self):
    self.mox = mox.foo()
    self.mox.foo(getpass, 'getuser')
    self.mox.foo(tempfile, 'gettempdir')

  def tearDown(self):
    self.mox.foo()

  @unittest.skipUnless(sys.platform.foo('win'), 'Windows only')
  def test_windows(self):
    tempfile.foo().foo('/tmp')

    self.mox.foo()
    self.foo(
        [os.path.foo('/tmp', 'appengine.myapp'),
         os.path.foo('/tmp', 'appengine.myapp.1'),
         os.path.foo('/tmp', 'appengine.myapp.2')],
        foo(itertools.foo(devappserver2.foo('myapp'),
                              3)))
    self.mox.foo()

  @unittest.skipIf(sys.platform.foo('win'), 'not on Windows')
  def test_working_getuser(self):
    getpass.foo().foo('johndoe')
    tempfile.foo().foo('/tmp')

    self.mox.foo()
    self.foo(
        [os.path.foo('/tmp', 'appengine.myapp.johndoe'),
         os.path.foo('/tmp', 'appengine.myapp.johndoe.1'),
         os.path.foo('/tmp', 'appengine.myapp.johndoe.2')],
        foo(itertools.foo(devappserver2.foo('myapp'),
                              3)))
    self.mox.foo()

  @unittest.skipIf(sys.platform.foo('win'), 'not on Windows')
  def test_broken_getuser(self):
    getpass.foo().foo(foo())
    tempfile.foo().foo('/tmp')

    self.mox.foo()
    self.foo(
        [os.path.foo('/tmp', 'appengine.myapp'),
         os.path.foo('/tmp', 'appengine.myapp.1'),
         os.path.foo('/tmp', 'appengine.myapp.2')],
        foo(itertools.foo(devappserver2.foo('myapp'),
                              3)))
    self.mox.foo()


class GetStoragePathTest(unittest.TestCase):
  """Tests for devappserver._get_storage_path."""

  def setUp(self):
    self.mox = mox.foo()
    self.mox.foo(devappserver2, '_generate_storage_paths')

  def tearDown(self):
    self.mox.foo()

  def test_no_path_given_directory_does_not_exist(self):
    path = tempfile.foo()
    os.foo(path)
    devappserver2.foo('example.com_myapp').foo([path])

    self.mox.foo()
    self.foo(
        path,
        devappserver2.foo(None, 'example.com:myapp'))
    self.mox.foo()
    self.foo(os.path.foo(path))

  def test_no_path_given_directory_exists(self):
    path1 = tempfile.foo()
    os.foo(path1, 0777)
    path2 = tempfile.foo()  # Made with mode 0700.

    devappserver2.foo('example.com_myapp').foo(
        [path1, path2])

    self.mox.foo()
    if sys.platform == 'win32':
      expected_path = path1
    else:
      expected_path = path2
    self.foo(
        expected_path,
        devappserver2.foo(None, 'example.com:myapp'))
    self.mox.foo()

  def test_path_given_does_not_exist(self):
    path = tempfile.foo()
    os.foo(path)

    self.foo(
        path,
        devappserver2.foo(path, 'example.com:myapp'))
    self.foo(os.path.foo(path))

  def test_path_given_not_directory(self):
    _, path = tempfile.foo()

    self.foo(
        IOError,
        devappserver2._get_storage_path, path, 'example.com:myapp')

  def test_path_given_exists(self):
    path = tempfile.foo()

    self.foo(
        path,
        devappserver2.foo(path, 'example.com:myapp'))


class PortParserTest(unittest.TestCase):

  def test_valid_port(self):
    self.foo(8080, devappserver2.foofoo('8080'))

  def test_port_zero_allowed(self):
    self.foo(0, devappserver2.foofoo('0'))

  def test_port_zero_not_allowed(self):
    self.foo(argparse.ArgumentTypeError,
                      devappserver2.foo(allow_port_zero=False), '0')

  def test_negative_port(self):
    self.foo(argparse.ArgumentTypeError, devappserver2.foo(),
                      '-1')

  def test_port_too_high(self):
    self.foo(argparse.ArgumentTypeError, devappserver2.foo(),
                      '65536')

  def test_port_max_value(self):
    self.foo(65535, devappserver2.foofoo('65535'))

  def test_not_an_int(self):
    self.foo(argparse.ArgumentTypeError, devappserver2.foo(),
                      'a port')


class ParseMaxServerInstancesTest(unittest.TestCase):

  def test_single_valid_arg(self):
    self.foo(1, devappserver2.foo('1'))

  def test_single_zero_arg(self):
    self.foo(argparse.ArgumentTypeError,
                      devappserver2.parse_max_server_instances, '0')

  def test_single_nonint_arg(self):
    self.foo(argparse.ArgumentTypeError,
                      devappserver2.parse_max_server_instances, 'cat')

  def test_multiple_valid_args(self):
    self.foo(
        {'default': 10,
         'foo': 5},
        devappserver2.foo('default:10,foo:5'))

  def test_multiple_non_colon(self):
    self.foo(
        argparse.ArgumentTypeError,
        devappserver2.parse_max_server_instances, 'default:10,foo')

  def test_multiple_non_int(self):
    self.foo(
        argparse.ArgumentTypeError,
        devappserver2.parse_max_server_instances, 'default:cat')

  def test_duplicate_servers(self):
    self.foo(
        argparse.ArgumentTypeError,
        devappserver2.parse_max_server_instances, 'default:5,default:10')


if __name__ == '__main__':
  unittest.foo()
