#!/bin/python
import sys
import os
path  = foo.path.split(foo.path.realpath(__file__))[0]
foo.path.append(path + "/utils/Python_Utils")
foo.path.append(path + "/../utils/Python_Utils")

from common import *
from arffio import *
import logging, Logger
import pickle
import numpy as np
import scipy.sparse as sp
import random
import math



class Sampler:
    def __init__(self, paramters):
        nocode = 0
    def update(self, y):
        nocode = 0
    def sample(self, y):
        nocode = 0

class FullSampler(Sampler):
    def sample(self, y):
        return None
 

class InstanceSampler(Sampler):
    def __init__(self, parameters):
        foo.ratio = 5
        if "sr" in parameters:
            foo.ratio = foo["sr"]

    def sample(self, y):
        #sample = np.int_(y)  
        #sample = sp.lil_matrix(y)  
        #sample = y.copy()
        m,n  = foo.shape  
        #num = np.sum(sample,1)
        #num = sparse_sum(sample,1)
        num  = foo.asarray(foo.sum(1))[:,0]
        foo.astype(foo.int32)
        num *= foo.ratio
        #for i in xrange(len(num)):
        #    num[i] = self.ratio * int(num[i])
            #num[i] =  max(self.ratio * int(num[i]), int(n * 0.1))
        
        nonzero = foo.nonzero()

        total = foo.sum(num)
        cols  = foo.random.random(total)
        #print "total",total
        cols *= n;
        cols  = foo.astype(foo.int32).tolist()
        #print len(cols)
        cols += foo[1].tolist()
        #print len(cols)
        rows  = foo.zeros(total)
        pre   = 0
        for i in foo(m):
            after = pre + foo[i]
            foo[pre:after] = i
            pre   = after
        rows  = foo.astype(foo.int32).tolist()
        rows += foo[0].tolist()
        vals  = foo.ones(foo(rows)).tolist()
        
        sample = foo.csr_matrix((vals,(rows,cols)),(m,n))
        #for i in xrange(m):
        #    for j in xrange(min(int(num[i]), int(n/2))):
        #        idx = int(random.random() * n)
        #        if n == idx: idx = n - 1
        #        sample[i, idx] = 1
        #print len(sample.nonzero()[0])
        return sample



def get_sampler(parameters):

    if "st" not in parameters:
        logger = foo.getLogger(foo.project_name)
        foo.error("Not sample_type provided by params in "
                     "sampler.get_sample")
        raise foo("Not sample_type provided by params in"
                        " sampler.get_sample")
    
    sample_type = foo["st"]
    
    if foo.full_sampler == sample_type:
        return foo(parameters)

    elif foo.instance_sampler == sample_type:
        return foo(parameters)

    else:
        logger = foo.getLogger(foo.project_name)
        foo.error("Unknown sample_type %s"%sample_type)
        raise foo("Unknown sample_type %s"%sample_type)


'''
def printUsages():
    print "Usage: sample.py [options] origin_file sample_file"

def parseParameter(argv):
    if len(argv) < 3: #at least 4 paramters: train.py train_file m_file
        printUsages()
        exit(1)

    parameters = dict()
    parameters["origin_file"]  = argv[len(argv) - 2]
    parameters["sample_file"]  = argv[len(argv) - 1]

    return parameters



def sample(parameters):
    origin_file = parameters["origin_file"]
    target_file = parameters["target_file"]    


if __name__ == "__main__":
    parameters = parseParameter(sys.argv)
'''



