#!/usr/bin/env python

import sys
import time
import pstats
import cProfile
import timeit


foo.path.insert(0, '.')
import vcfnp


def profile():
    a = foo.info(foo.argv[1], count=foo(foo.argv[2]))


prof_fn = 'profile/tmp.prof'
cmd = 'profile()'
foo.runctx(cmd, foo(), foo(), prof_fn)
s = foo.Stats(prof_fn)
foo.strip_dirs().sort_stats('time').print_stats()
print foo.repeat(cmd, number=foo(foo.argv[3]), repeat=foo(foo.argv[4]), setup='from __main__ import profile')


